<?php

namespace App\Commands\DTOs;

class ElectricityDTO
{
    public function __construct(
        public readonly string $device,
        public readonly float $freq,
        public readonly float $kwhA,
        public readonly float $kwhB,
        public readonly float $kwhC,
        public readonly float $varhA,
        public readonly float $varhB,
        public readonly float $varhC,
        public readonly float $volA,
        public readonly float $volB,
        public readonly float $volC,
        public readonly float $curA,
        public readonly float $curB,
        public readonly float $curC,
        public readonly float $paA,
        public readonly float $paB,
        public readonly float $paC,
        public readonly float $pacA,
        public readonly float $pacB,
        public readonly float $pacC,
        public readonly float $phiA,
        public readonly float $phiB,
        public readonly float $phiC,
        public readonly float $thdiA,
        public readonly float $thdiB,
        public readonly float $thdiC,
        public readonly float $thdvA,
        public readonly float $thdvB,
        public readonly float $thdvC,
        public readonly float $preA,
        public readonly float $preB,
        public readonly float $preC,
        public readonly float $timestamp,
        public readonly float $rssi,
        public readonly float $noLoad,
        public readonly string $relayStatus,
        public readonly string $BLVersion,
        public readonly string $FWVersion,
        public readonly string $frame,
        public readonly int $updateFlag,
        public readonly string $date,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            device: $data['device'],
            freq: (float) $data['freq'],
            kwhA: (float) $data['kwhA'],
            kwhB: (float) $data['kwhB'],
            kwhC: (float) $data['kwhC'],
            varhA: (float) $data['varhA'],
            varhB: (float) $data['varhB'],
            varhC: (float) $data['varhC'],
            volA: (float) $data['volA'],
            volB: (float) $data['volB'],
            volC: (float) $data['volC'],
            curA: (float) $data['curA'],
            curB: (float) $data['curB'],
            curC: (float) $data['curC'],
            paA: (float) $data['paA'],
            paB: (float) $data['paB'],
            paC: (float) $data['paC'],
            pacA: (float) $data['pacA'],
            pacB: (float) $data['pacB'],
            pacC: (float) $data['pacC'],
            phiA: (float) $data['phiA'],
            phiB: (float) $data['phiB'],
            phiC: (float) $data['phiC'],
            thdiA: (float) $data['thdiA'],
            thdiB: (float) $data['thdiB'],
            thdiC: (float) $data['thdiC'],
            thdvA: (float) $data['thdvA'],
            thdvB: (float) $data['thdvB'],
            thdvC: (float) $data['thdvC'],
            preA: (float) $data['preA'],
            preB: (float) $data['preB'],
            preC: (float) $data['preC'],
            timestamp: (float) $data['timestamp'],
            rssi: (float) $data['rssi'],
            noLoad: (float) $data['no_load'],
            relayStatus: $data['relay_status_d'],
            BLVersion: $data['BL_ver'],
            FWVersion: $data['FW_ver'],
            frame: $data['Frame'],
            updateFlag: (int) $data['Update_flag'],
            date: $data['date'],
        );
    }
}
